---
title: "Analytics Engineer Challange"
author: "Vincenzo Grasso - vincenzo.grass@gmail.com"
date: "1/27/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## A - Message Conversion Rates

This is the typical example of Simpon's Paradox aka a phenomenon in in which a trend appears in groups of data but disappears or reverses when the groups are combined.


```{r message=FALSE, warning=FALSE}
library(tidyverse)

y <- rep(0:1, c(4, 4))
trt <- rep(c("A", "B"), 4)
platform <- rep(c("IOS", "IOS", "Android", "Android"), 2)
all_cnt <- c(174000, 540000, 526000, 160000)
subscriptions <- c(16200, 46800, 38400, 11000)
non_subscriptions <- all_cnt - subscriptions

weight <- c(non_subscriptions, subscriptions)

df <- tibble(
  y,
  trt = factor(trt, levels = c("B", "A")),
  platform,
  weight
)

print(df)
```



Resulting in:

```{r}
df_long <- df %>% 
  rowwise() %>% 
  mutate(ids = list(seq(1, weight))) %>% 
  unnest(ids)

summary(lm(y ~ trt + platform, df_long)) 
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
